name: "nocodb.truva.in"

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Checkout truva branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: truva

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Get commit hash
        id: commit-hash
        run: |
          echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Update version in package.json
        run: |
          cd packages/nocodb
          jq --arg VERSION "$VERSION" '.version = $VERSION' package.json > tmp.json
          mv tmp.json package.json
        env:
          VERSION: truva-${{ steps.commit-hash.outputs.commit_hash }}

      - name: Build NocoDB SDK
        run: |
          cd packages/nocodb-sdk
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: Build NocoDB GUI
        run: |
          cd packages/nc-gui
          pnpm install --no-frozen-lockfile
          pnpm run build:copy
          rsync -rvzh ./dist/ ../nocodb/docker/nc-gui/

      - name: Copy NocoDB GUI Library (nc-lib-gui)
        run: |
          mkdir -p packages/nocodb/docker/nc-lib-gui/
          cp -rv packages/nc-lib-gui/* packages/nocodb/docker/nc-lib-gui/

      - name: Build NocoDB Backend
        run: |
          cd packages/nocodb
          pnpm run build:obfuscate
          pnpm run docker:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push the image to Amazon ECR
        id: build-docker-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: truva-${{ steps.commit-hash.outputs.commit_hash }}
        run: |
          cd packages/nocodb
          docker build . -f Dockerfile.truva -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-on-ecs:
    runs-on: ubuntu-22.04
    needs: build-image
    steps:
      - name: Checkout truva branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: truva

      - name: Get commit hash
        id: commit-hash
        run: |
          echo "commit_hash=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download ECS Task Definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --query taskDefinition > base-task-definition.json

      - name: Sanitize Task Definition File
        run: |
          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
          base-task-definition.json > pre-image-task-definition.json

      - name: Update Task Definition with New Image
        run: |
          jq --arg ECR_REGISTRY "$ECR_REGISTRY" \
            --arg ECR_REPOSITORY "$ECR_REPOSITORY" \
            --arg IMAGE_TAG "$IMAGE_TAG" \
            '.containerDefinitions[0].image = ($ECR_REGISTRY + "/" + $ECR_REPOSITORY + ":" + $IMAGE_TAG)' \
            pre-image-task-definition.json > deploy-task-definition.json
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: truva-${{ steps.commit-hash.outputs.commit_hash }}

      - name: Register New Task Definition
        id: register-task
        run: |
          aws ecs register-task-definition --cli-input-json file://deploy-task-definition.json | \
          jq -r '.taskDefinition.taskDefinitionArn'

      - name: Update ECS Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --enable-execute-command \
          --force-new-deployment \
          --desired-count ${{ secrets.ECS_DESIRED_COUNT }}
