name: "nocodb.truva.in"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true

jobs:
  build-image:
    runs-on: ubuntu-22.04
    env:
      working-directory: ./packages/nocodb
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Checkout truva branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: truva

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Update version in package.json
        run: |
          cd packages/nocodb
          jq --arg VERSION "$VERSION" '.version = $VERSION' package.json > tmp.json
          mv tmp.json package.json
        env:
          VERSION: ${{ inputs.tag }}

      - name: Build NocoDB SDK
        run: |
          cd packages/nocodb-sdk
          pnpm install
          pnpm run build

      - name: Build NocoDB GUI
        run: |
          cd packages/nc-gui
          pnpm install
          pnpm run generate
          rsync -rvzh ./dist/ ../nocodb/docker/nc-gui/

      - name: Build NocoDB Backend
        run: |
          cd packages/nocodb
          pnpm run build:obfuscate
          npx tsc -p tsconfig.json
          npx tsc -p tsconfig.module.json
          pnpm run docker:build    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push the image to Amazon ECR
        id: build-docker-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ inputs.tag }}
        run: |
          cd packages/nocodb
          docker build . -f Dockerfile.local -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-on-ecs:
    runs-on: ubuntu-22.04
    needs: build-image
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download ECS Task Definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --query taskDefinition > base-task-definition.json

      - name: Sanitize Task Definition File
        run: |
          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
          base-task-definition.json > pre-image-task-definition.json

      - name: Update Task Definition with New Image
        run: |
          jq '.containerDefinitions[0].image = "${{ steps.login-ecr.outputs.registry }}/${{ secrets.REPO_NAME }}:${{ inputs.tag }}"' \
          pre-image-task-definition.json > deploy-task-definition.json

      - name: Register New Task Definition
        id: register-task
        run: |
          aws ecs register-task-definition --cli-input-json file://deploy-task-definition.json | \
          jq -r '.taskDefinition.taskDefinitionArn'

      - name: Update ECS Service
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --enable-execute-command \
          --force-new-deployment \
          --desired-count ${{ secrets.ECS_DESIRED_COUNT }}
